[tool.poetry]
name = "autodeal-sync"
version = "0.1.0"
description = "Integracao x AutoDeal"
authors = ["Renan Domingos <rna.domingos@hotmail.com>"]
readme = "README.md"

packages = [
  { include = "*", from = "src" }
]

[tool.poetry.dependencies]
python = ">=3.12"
requests = "^2.32.3"
pandas = "^2.3.0"
sqlalchemy = "^2.0.41"
pymysql = "^1.1.1"
python-dotenv = "^1.1.1"
pandera = "^0.24.0"
psycopg2 = "^2.9.12"

[tool.poetry.scripts]
seed-companies = "utils.seed_companies:seed_companies"
dev = "src.main:main"

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"